root: true
parser: "@typescript-eslint/parser"
parserOptions:
  project: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:@typescript-eslint/strict-type-checked
  - plugin:@typescript-eslint/stylistic-type-checked
  - plugin:prettier/recommended
  - plugin:deprecation/recommended
  # - plugin:perfectionist/recommended-natural
plugins:
  - unused-imports
rules:
  "@typescript-eslint/no-non-null-assertion": off
  "@typescript-eslint/consistent-type-definitions": off
  "@typescript-eslint/restrict-template-expressions":
    - error
    - allowNullish: true
