services:
  server:
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
  caddy:
    image: caddy
    ports:
      - 80:80
      - 443:443
      - 9017:9017
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
  whoami:
    image: traefik/whoami

volumes:
  caddy_data:
  caddy_config: